### ISSUE TITLE
建议建个qq群交流，方便反馈脚本问题（刚建了一个群，喵币组队互刷：825455296）

### ISSUE THREAD

**Issue by jw-star** [jiayiwang5/TaoBaoScripts#10]

**Comment by el-sl** [comment]
小米6 好不容易下载下来了，运行却失败了！

**Comment by wangyuxiang985** [comment]
> 小米6 好不容易下载下来了，运行却失败了！

同小米钉子户，你好丫哈哈

**Comment by el-sl** [comment]
> 
> 
> > 小米6 好不容易下载下来了，运行却失败了！
> 
> 同小米钉子户，你好丫哈哈

手机买新不买旧，除非是小米6！

**Comment by jayeew** [comment]
> 小米6 好不容易下载下来了，运行却失败了！

钉子户你咋失败了

**Comment by el-sl** [comment]
> 
> 
> > 小米6 好不容易下载下来了，运行却失败了！
> 
> 钉子户你咋失败了
![图片](https://user-images.githubusercontent.com/68845324/96669919-cf5b0800-1390-11eb-8ac8-fc8cbeb71c42.png)
首页进去启动脚本后，速度设为3，一直在这个界面，根本就不进活动！ 桑心！

**Comment by jw-star** [comment]
> 小米6 好不容易下载下来了，运行却失败了！

可以看下日志报错的内容

**Comment by jayeew** [comment]
> > > 小米6 好不容易下载下来了，运行却失败了！
> > 
> > 
> > 钉子户你咋失败了
> > ![图片](https://user-images.githubusercontent.com/68845324/96669919-cf5b0800-1390-11eb-8ac8-fc8cbeb71c42.png)
> > 首页进去启动脚本后，速度设为3，一直在这个界面，根本就不进活动！ 桑心！

下最新的试试，我估计3还是快了

**Comment by jw-star** [comment]
刚建了一个群，喵币组队互刷：825455296

**Comment by el-sl** [comment]
> 
> 
> > > > 小米6 好不容易下载下来了，运行却失败了！
> > > 
> > > 
> > > 钉子户你咋失败了
> > > ![图片](https://user-images.githubusercontent.com/68845324/96669919-cf5b0800-1390-11eb-8ac8-fc8cbeb71c42.png)
> > > 首页进去启动脚本后，速度设为3，一直在这个界面，根本就不进活动！ 桑心！
> 
> 下最新的试试，我估计3还是快了

好的，好的！
