### ISSUE TITLE
小米10 95行报错了

### ISSUE THREAD

**Issue by Nosirc** [jiayiwang5/TaoBaoScripts#14]
![Screenshot_2020-10-21-12-59-41-681_com taobao tao](https://user-images.githubusercontent.com/23207140/96675459-8198cc80-139d-11eb-8cd0-32da949022fc.jpg)

**Comment by jayeew** [comment]
道歉 尝试多次没法复现你的问题 请问你延迟开的几

**Comment by Nosirc** [comment]
4

**Comment by Nosirc** [comment]
可能是我安装的APP有问题,用了你的就好了
