### ISSUE TITLE
这个提示是啥意思呢？？？

### ISSUE THREAD

**Issue by SleeeeeepyZ** [jiayiwang5/TaoBaoScripts#15]
![6c579c808044ed3ccac4a0eb848d223](https://user-images.githubusercontent.com/38531056/96675535-a725d600-139d-11eb-82b2-1c51e7d1e37f.png)

**Comment by jayeew** [comment]
道歉 不清楚诶，请问是什么设备，系统版本，auto版本

**Comment by SleeeeeepyZ** [comment]
设备是坚果pro2，安卓7.1.1的，auto是4.0.1 beta

**Comment by jayeew** [comment]
> 设备是坚果pro2，安卓7.1.1的，auto是4.0.1 beta

道歉 我和身边众人多次尝试都未能复现此错误 猜测可能个人情况，暂无法解决

**Comment by jayeew** [comment]
另外 请更新最新版尝试下
