### ISSUE TITLE
您好，问一下进入登录淘宝特价版那个活动是不是没屏蔽掉？

### ISSUE THREAD

**Issue by wangyuxiang985** [jiayiwang5/TaoBaoScripts#19]
更新autojs4.0后正常执行了，但是去完成标签下有个登录淘宝特价版送红包的任务，这个是否应该屏蔽掉呢，执行到这里的时候出现了死循环，一直点进去停留15s出来再继续。

**Comment by jayeew** [comment]
不会啊 我有特别处理啊，你下新的试试

**Comment by wangyuxiang985** [comment]
> 不会啊 我有特别处理啊，你下新的试试

好哒，我更新一下

**Comment by wangyuxiang985** [comment]
👍
