### ISSUE TITLE
一开始就运行不成功了

### ISSUE THREAD

**Issue by github-plus** [jiayiwang5/TaoBaoScripts#2]
![image](https://user-images.githubusercontent.com/68683753/96661554-e2fd7300-137e-11eb-8638-fa082786ada7.png

**Comment by jayeew** [comment]
请问开启无障碍权限了吗

**Comment by github-plus** [comment]
我这边显示是开了的

**Comment by jayeew** [comment]
> 我这边显示是开了的

显示权限拒绝，操作被oppo的colorOS安全中心拦截了，我手机暂时没有oppo机型测试

**Comment by github-plus** [comment]
老哥有没有电脑浏览器刷的，就想刷京东京豆一样，用浏览器刷

**Comment by L0yy** [comment]
华为 和楼主同样权限问题，报错一样，未解决

**Comment by wangyuxiang985** [comment]
小米6执行到领猫币中心的时候报如下错误：
Can't find method com.stardust.autojs.core.accessibility.UiSelector.findOnce(). (<main_48>#30)
  at script(<main_48>:30)

**Comment by jayeew** [comment]
> 小米6执行到领猫币中心的时候报如下错误：
> Can't find method com.stardust.autojs.core.accessibility.UiSelector.findOnce(). (<main_48>#30)
> at script(<main_48>:30)

请更新脚本试试，我改了脚本后找不到出错位置，  不好意思

**Comment by wangyuxiang985** [comment]
> > 小米6执行到领猫币中心的时候报如下错误：
> > 找不到方法com.stardust.autojs.core.accessibility.UiSelector.findOnce（）。（<main_48>＃30）
> > 在脚本（<main_48>：30）
> 
> 请更新脚本试试，我改了脚本后找不到错误位置，不好意思

你好，还是一样的错误，参数选择的2，
![执行报错图.jpg](https://i.loli.net/2020/10/21/bA5ueI3LarnjKdN.jpg)

**Comment by jayeew** [comment]
> > > 小米6执行到领猫币中心的时候报如下错误：
> > > 找不到方法com.stardust.autojs.core.accessibility.UiSelector.findOnce（）。（<main_48>＃30）
> > > 在脚本（<main_48>：30）
> > 
> > 
> > 请更新脚本试试，我改了脚本后找不到错误位置，不好意思
> 
> 你好，还是一样的错误，参数选择的2，
> ![执行报错图.jpg](https://camo.githubusercontent.com/333aff6df00f0bf9930e18f12875b9f0261c2527/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31302f32312f624135756549334c61726e6a4b644e2e6a7067)

尝试多次，周围几个人和我都无法复现你的错误，等我慢慢查查

**Comment by jin019649** [comment]
我把/* *\删除就可以运行了

**Comment by github-plus** [comment]
老哥，不好意思，是我的悬浮窗没开
