### ISSUE TITLE
疑问：这个脚本是只会完成20次那个任务吗？

### ISSUE THREAD

**Issue by LamentolaQ** [jiayiwang5/TaoBaoScripts#20]
脚本有在执行，执行完20次浏览那个任务之后就说任务执行完了。然后也没有拍猫

**Comment by aLIEz-xue** [comment]
我这边执行完，有拍猫这个操作

**Comment by jiayiwang5** [comment]
> 脚本有在执行，执行完20次浏览那个任务之后就说任务执行完了。然后也没有拍猫

请问日志具体卡到哪里?没弹输入框吗

**Comment by LamentolaQ** [comment]
> > 脚本有在执行，执行完20次浏览那个任务之后就说任务执行完了。然后也没有拍猫
> 
> 请问日志具体卡到哪里?没弹输入框吗

没弹输入框。就是提示任务完成了，然后我看还有很多没完成的。但是我看次数不多就手动完成了所以无法截图了。明天再试下给你截图
