### ISSUE TITLE
建议使用auto.waitFor()

### ISSUE THREAD

**Issue by mengbo1991** [jiayiwang5/TaoBaoScripts#22]
建议使用auto.waitFor()和auto.setMode()代替该函数，因为auto()函数如果无障碍服务未启动会停止脚本；而auto.waitFor()则会在在无障碍服务启动后继续运行。
https://hyb1996.github.io/AutoJs-Docs/#/widgetsBasedAutomation?id=autowaitfor

**Comment by jayeew** [comment]
谢谢反馈 很有价值！
