### ISSUE TITLE
刷脚本被检测了

### ISSUE THREAD

**Issue by Castle1984** [jiayiwang5/TaoBaoScripts#25]
正常逛店铺是3w币，这个刷了每个店铺只有300，被黑号了，555

**Comment by xuanyuanlei1020** [comment]
从技术层面来说 , 他们是怎么检测到的?

**Comment by 9xiao** [comment]
我也变成300了Orz

**Comment by mustssr** [comment]
> 从技术层面来说 , 他们是怎么检测到的?

可能是用脚本的点击区域高度一直，然后把点击位置重复位置很高的都判定为脚本

**Comment by TernenceZhou** [comment]
我也是这样，早上所有的都是100 200这样的了 。猜测也只能是被封了~~

**Comment by jayeew** [comment]
我试了试，我的情况是，他能检测auto.js进程，我打开这个软件不跑脚本淘宝一样黑，杀掉进程就ok了

**Comment by Perplexed-H** [comment]
> 
> 
> 我试了试，我的情况是，他能检测auto.js进程，我打开这个软件不跑脚本淘宝一样黑，杀掉进程就ok了

+1，auto.js杀了就好了，从设置里杀，不要只清后台

**Comment by Castle1984** [comment]
刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务较少，auto.js执行脚本没出现什么问题，是正常币

**Comment by PegasusCharles** [comment]
> 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务最多，auto.js执行脚本没出现什么问题，是正常币

哥们实验的🍑的版本是多少

**Comment by JackKuang** [comment]
我刚刚卸载了auto.js，恢复了

**Comment by koen100** [comment]
> > 我试了试，我的情况是，他能检测auto.js进程，我打开这个软件不跑脚本淘宝一样黑，杀掉进程就ok了
> 
> +1，auto.js杀了就好了，从设置里杀，不要只清后台

杀掉进程 脚本还会运行吗

**Comment by kings1990** [comment]
> 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务较少，auto.js执行脚本没出现什么问题，是正常币

随机点击和延时币正常？

**Comment by koen100** [comment]
> > 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务较少，auto.js执行脚本没出现什么问题，是正常币
> 
> 随机点击和延时币正常？

代码不太看得懂,不知道有没有随机点击,延迟应该是固定的,我降低了淘宝版本后运行脚本金币正常,

**Comment by jayeew** [comment]
> > > 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务较少，auto.js执行脚本没出现什么问题，是正常币
> > 
> > 
> > 随机点击和延时币正常？
> 
> 代码不太看得懂,不知道有没有随机点击,延迟应该是固定的,我降低了淘宝版本后运行脚本金币正常,

可用的旧淘宝从哪下啊，我试试

**Comment by Castle1984** [comment]
> > 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务最多，auto.js执行脚本没出现什么问题，是正常币
> 
> 哥们实验的🍑的版本是多少

说了啊，是9.5啊

**Comment by Castle1984** [comment]
> > > > 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务较少，auto.js执行脚本没出现什么问题，是正常币
> > > 
> > > 
> > > 随机点击和延时币正常？
> > 
> > 
> > 代码不太看得懂,不知道有没有随机点击,延迟应该是固定的,我降低了淘宝版本后运行脚本金币正常,
> 
> 可用的旧淘宝从哪下啊，我试试

https://www.wandoujia.com/apps/32267/history_v274

**Comment by Castle1984** [comment]
> > 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务较少，auto.js执行脚本没出现什么问题，是正常币
> 
> 随机点击和延时币正常？

我觉得我表述挺清楚的啊，我是直接用的python+adb写了个程序对手机上的淘宝进行调试的，也没有用autojs，币的数量就给了100

**Comment by jayeew** [comment]
> > > 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务较少，auto.js执行脚本没出现什么问题，是正常币
> > 
> > 
> > 随机点击和延时币正常？
> 
> 我觉得我表述挺清楚的啊，我是直接用的python+adb写了个程序对手机上的淘宝进行调试的，也没有用autojs，币的数量就给了100

谢谢反馈 ！

**Comment by kings1990** [comment]
> > > 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务较少，auto.js执行脚本没出现什么问题，是正常币
> > 
> > 
> > 随机点击和延时币正常？
> 
> 我觉得我表述挺清楚的啊，我是直接用的python+adb写了个程序对手机上的淘宝进行调试的，也没有用autojs，币的数量就给了100

所以结论是淘宝版本降低就可以了？

**Comment by XiaoqiangZhou** [comment]
> > > > 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务较少，auto.js执行脚本没出现什么问题，是正常币
> > > 
> > > 
> > > 随机点击和延时币正常？
> > 
> > 
> > 我觉得我表述挺清楚的啊，我是直接用的python+adb写了个程序对手机上的淘宝进行调试的，也没有用autojs，币的数量就给了100
> 
> 所以结论是淘宝版本降低就可以了？

我卸载现在的双11版本，使用淘宝9.5版本后，是可以正常刷脚本的。只需打开悬浮窗权限和无障碍权限

**Comment by BlademasterQAQ** [comment]
> > > > > 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务较少，auto.js执行脚本没出现什么问题，是正常币
> > > > 
> > > > 
> > > > 随机点击和延时币正常？
> > > 
> > > 
> > > 我觉得我表述挺清楚的啊，我是直接用的python+adb写了个程序对手机上的淘宝进行调试的，也没有用autojs，币的数量就给了100
> > 
> > 
> > 所以结论是淘宝版本降低就可以了？
> 
> 我卸载现在的双11版本，使用淘宝9.5版本后，是可以正常刷脚本的。只需打开悬浮窗权限和无障碍权限

感谢。
我开始以为是淘宝检测了无障碍服务，一旦使用“执行手势”权限，就拉黑（其他不使用这个权限的，如输入法，不会被拉黑），结果发现华为的“会员中心”也使用到这个“执行手势”权限，但是不会被拉黑。而我另外两个脚本软件仅仅是运行无障碍就被拉黑了。如果按上面的说法，淘宝通过检测脚本软件的进程来拉黑，那么可以试试只后台运行autojs而不提供无障碍权限来测试（我已经卸载了最新版，无法测试，欢迎补充）。如果是这样，说明允许无障碍确实是会唤醒应用的。

提供两个解决方案：
1.（根据测试，一定可行）去[淘宝旧版本下载](https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=taobao)回退淘宝版本到9.5。
2.（猜测可行）更改autojs的包名，重新编译。

**Comment by jayeew** [comment]
感谢🙏楼上多位反馈，个人猜测淘宝有个app黑名单，可以检测进程。也有用auto.js源代码重新编辑改包名想法，一直懒得弄。
回退淘宝9.5版本实测可用，但脚本逻辑出错，可能控件有变化，我会找时间修改。

**Comment by BlademasterQAQ** [comment]
> > > > > > 刚试了一下，用了python adb方式对手机调试，采用随机点击+随机时延的方式，结果还是出现了100 200的情况。然后我怀疑是我更新了淘宝，于是重新安装了9.5版本，由于剩下的任务较少，auto.js执行脚本没出现什么问题，是正常币
> > > > > 
> > > > > 
> > > > > 随机点击和延时币正常？
> > > > 
> > > > 
> > > > 我觉得我表述挺清楚的啊，我是直接用的python+adb写了个程序对手机上的淘宝进行调试的，也没有用autojs，币的数量就给了100
> > > 
> > > 
> > > 所以结论是淘宝版本降低就可以了？
> > 
> > 
> > 我卸载现在的双11版本，使用淘宝9.5版本后，是可以正常刷脚本的。只需打开悬浮窗权限和无障碍权限
> 
> 感谢。
> 我开始以为是淘宝检测了无障碍服务，一旦使用“执行手势”权限，就拉黑（其他不使用这个权限的，如输入法，不会被拉黑），结果发现华为的“会员中心”也使用到这个“执行手势”权限，但是不会被拉黑。而我另外两个脚本软件仅仅是运行无障碍就被拉黑了。如果按上面的说法，淘宝通过检测脚本软件的进程来拉黑，那么可以试试只后台运行autojs而不提供无障碍权限来测试（我已经卸载了最新版，无法测试，欢迎补充）。如果是这样，说明允许无障碍确实是会唤醒应用的。
> 
> 提供两个解决方案：
> 1.（根据测试，一定可行）去[淘宝旧版本下载](https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=taobao)回退淘宝版本到9.5。
> 2.（猜测可行）更改autojs的包名，重新编译。

实测只后台运行autojs而不提供无障碍权限，并不会被淘宝黑名单，淘宝检测的是无障碍的进程？等一个大神解答。

**Comment by clj12081103** [comment]
> 感谢🙏楼上多位反馈，个人猜测淘宝有个app黑名单，可以检测进程。也有用auto.js源代码重新编辑改包名想法，一直懒得弄。
> 回退淘宝9.5版本实测可用，但脚本逻辑出错，可能控件有变化，我会找时间修改。

所以现在是要下载9.5版本的淘宝才能用吗，还是说用最新的脚本就行了

**Comment by jayeew** [comment]
> > 感谢🙏楼上多位反馈，个人猜测淘宝有个app黑名单，可以检测进程。也有用auto.js源代码重新编辑改包名想法，一直懒得弄。
> > 回退淘宝9.5版本实测可用，但脚本逻辑出错，可能控件有变化，我会找时间修改。
> 
> 所以现在是要下载9.5版本的淘宝才能用吗，还是说用最新的脚本就行了

用9.5

**Comment by wangyuxiang985** [comment]
> > > 感谢🙏楼上多位反馈，个人猜测淘宝有个app黑名单，可以检测进程。也有用auto.js源代码重新编辑改包名想法，一直懒得弄。
> > > 回退淘宝9.5版本实测可用，但脚本逻辑出错，可能控件有变化，我会找时间修改。
> > 
> > 
> > 所以现在是要下载9.5版本的淘宝才能用吗，还是说用最新的脚本就行了
> 
> 用9.5

9.5是正常的，但是你们都能跳过登录特价版吗？我的刷到这儿之后就一直死循环了

**Comment by zhzhch335** [comment]
> 感谢楼上多位反馈，个人猜测淘宝有个app黑名单，可以检测进程。也有用auto.js源代码重新编辑改包名想法，一直懒得弄。
> 回退淘宝9.5版本实测可用，但脚本逻辑出错，可能控件有变化，我会找时间修改。

我感觉改包名应该没用，如果只是检测包名的话，直接把脚本打包apk随便起一个包名应该没问题的。但是事实上自己打包出来的apk安装后依然会被1%

**Comment by clj12081103** [comment]
> > 感谢楼上多位反馈，个人猜测淘宝有个app黑名单，可以检测进程。也有用auto.js源代码重新编辑改包名想法，一直懒得弄。
> > 回退淘宝9.5版本实测可用，但脚本逻辑出错，可能控件有变化，我会找时间修改。
> 
> 我感觉改包名应该没用，如果只是检测包名的话，直接把脚本打包apk随便起一个包名应该没问题的。但是事实上自己打包出来的apk安装后依然会被1%

测试过了，改包名确实不行。

**Comment by jayeew** [comment]
> > > > 感谢pray楼上多位反馈，个人猜测淘宝有个app黑名单，可以检测进程。也有用auto.js源代码重新编辑改包名想法，一直懒得弄。
> > > > 回退淘宝9.5版本实测可用，但脚本逻辑出错，可能控件有变化，我会找时间修改。
> > > 
> > > 
> > > 所以现在是要下载9.5版本的淘宝才能用吗，还是说用最新的脚本就行了
> > 
> > 
> > 用9.5
> 
> 9.5是正常的，但是你们都能跳过登录特价版吗？我的刷到这儿之后就一直死循环了

已修复

**Comment by jayeew** [comment]
> > > 感谢楼上多位反馈，个人猜测淘宝有个app黑名单，可以检测进程。也有用auto.js源代码重新编辑改包名想法，一直懒得弄。
> > > 回退淘宝9.5版本实测可用，但脚本逻辑出错，可能控件有变化，我会找时间修改。
> > 
> > 
> > 我感觉改包名应该没用，如果只是检测包名的话，直接把脚本打包apk随便起一个包名应该没问题的。但是事实上自己打包出来的apk安装后依然会被1%
> 
> 测试过了，改包名确实不行。

感谢反馈

**Comment by mengbo1991** [comment]
华为多屏协同用鼠标操作也是100。。。检测搞不懂

**Comment by BlademasterQAQ** [comment]
> 华为多屏协同用鼠标操作也是100。。。检测搞不懂

感谢提供信息

**Comment by BlademasterQAQ** [comment]
有人试过用root过的Android系统跑按键精灵这种脚本吗？不知道是不是也会被检测。

**Comment by jayeew** [comment]
> 华为多屏协同用鼠标操作也是100。。。检测搞不懂

小马哥这么小气吗

**Comment by mengbo1991** [comment]
> > 华为多屏协同用鼠标操作也是100。。。检测搞不懂
> 
> 小马哥这么小气吗

检测点和面的操作？

**Comment by BlademasterQAQ** [comment]
> > > 华为多屏协同用鼠标操作也是100。。。检测搞不懂
> > 
> > 
> > 小马哥这么小气吗
> 
> 检测点和面的操作？

无法解释autojs仅仅获取无障碍权限在后台也被ban
也可能是有多种检测手段一起

**Comment by Mit2g** [comment]
> 感谢🙏楼上多位反馈，个人猜测淘宝有个app黑名单，可以检测进程。也有用auto.js源代码重新编辑改包名想法，一直懒得弄。
> 回退淘宝9.5版本实测可用，但脚本逻辑出错，可能控件有变化，我会找时间修改。

改包名应该是无效的 早前有使用autojs自行打包的程序 包名与autojs并不一致 但依然会被检测 个人判断可能与进程有关
如果需要可以提供上面提到的程序

**Comment by jayeew** [comment]
> > 感谢pray楼上多位反馈，个人猜测淘宝有个app黑名单，可以检测进程。也有用auto.js源代码重新编辑改包名想法，一直懒得弄。
> > 回退淘宝9.5版本实测可用，但脚本逻辑出错，可能控件有变化，我会找时间修改。
> 
> 改包名应该是无效的 早前有使用autojs自行打包的程序 包名与autojs并不一致 但依然会被检测 个人判断可能与进程有关
> 如果需要可以提供上面提到的程序

懒得追究了，，，能用赶紧用吧，不知道能活几天

**Comment by 1379** [comment]
9.5有很多个小版本，9.5.17可以吗

**Comment by FridayLiu** [comment]
> 9.5有很多个小版本，9.5.17可以吗

实测可以
