### ISSUE TITLE
tb已经有了检测机制

### ISSUE THREAD

**Issue by Perplexed-H** [jiayiwang5/TaoBaoScripts#26]
估计是检测到了进程auto.js，从设置里结束运行该程序即可恢复正常
也有人说是更新淘宝后，尝试安装回滚老版本试试

**Comment by jayeew** [comment]
嗯 你看看另一个issue，我们有讨论

**Comment by iblue007** [comment]
正常进程就是包名吧，换个包名是不是就可以了
