### ISSUE TITLE
拍猫好像不行呀 

### ISSUE THREAD

**Issue by iblue007** [jiayiwang5/TaoBaoScripts#31]

**Comment by jayeew** [comment]
怎么说 没拍还是咋的

**Comment by iblue007** [comment]
> 怎么说 没拍还是咋的

设置了拍猫次数后，显示要去拍猫了，然后就提示完活儿了

**Comment by jayeew** [comment]
奇怪诶 我没遇到过也没法复现你觉得错误

**Comment by iblue007** [comment]
> 奇怪诶 我没遇到过也没法复现你觉得错误

我是淘宝8.7.1.1的版本，你是9.5还是最新？

**Comment by jayeew** [comment]
> > 奇怪诶 我没遇到过也没法复现你觉得错误
> 
> 我是淘宝8.7.1.1的版本，你是9.5还是最新？

9.5的

**Comment by CfortWang** [comment]
> 怎么说 没拍还是咋的

拍猫结束打印完活是不是就结束了

**Comment by iblue007** [comment]
> 打印完活是不

是呀 ，

> > 怎么说 没拍还是咋的
> 
> 拍猫结束打印完活是不是就结束了



> > 怎么说 没拍还是咋的
> 
> 拍猫结束打印完活是不是就结束了

是呀就结束了

**Comment by iblue007** [comment]
> > > 奇怪诶 我没遇到过也没法复现你觉得错误
> > 
> > 
> > 我是淘宝8.7.1.1的版本，你是9.5还是最新？
> 
> 9.5的

我把拍猫的代码单独用vccode运行，居然可以拍猫，但是拍了可能一百下左右，再拍就没有反映了，淘宝可能不能一直拍吧？你有试过可以拍多少下？

**Comment by jayeew** [comment]
> > > > 奇怪诶 我没遇到过也没法复现你觉得错误
> > > 
> > > 
> > > 我是淘宝8.7.1.1的版本，你是9.5还是最新？
> > 
> > 
> > 9.5的
> 
> 我把拍猫的代码单独用vccode运行，居然可以拍猫，但是拍了可能一百下左右，再拍就没有反映了，淘宝可能不能一直拍吧？你有试过可以拍多少下？

我拍一千下，后来再拍就没钱了

**Comment by CfortWang** [comment]
> > > > 奇怪诶 我没遇到过也没法复现你觉得错误
> > > 
> > > 
> > > 我是淘宝8.7.1.1的版本，你是9.5还是最新？
> > 
> > 
> > 9.5的
> 
> 我把拍猫的代码单独用vccode运行，居然可以拍猫，但是拍了可能一百下左右，再拍就没有反映了，淘宝可能不能一直拍吧？你有试过可以拍多少下？

666下，没跑完就没收益了，但是它会跟你互动

**Comment by iblue007** [comment]
> > > > > 奇怪诶 我没遇到过也没法复现你觉得错误
> > > > 
> > > > 
> > > > 我是淘宝8.7.1.1的版本，你是9.5还是最新？
> > > 
> > > 
> > > 9.5的
> > 
> > 
> > 我把拍猫的代码单独用vccode运行，居然可以拍猫，但是拍了可能一百下左右，再拍就没有反映了，淘宝可能不能一直拍吧？你有试过可以拍多少下？
> 
> 我拍一千下，后来再拍就没钱了

那应该是有拍的次数限制吧

**Comment by iblue007** [comment]
> > > > > 奇怪诶 我没遇到过也没法复现你觉得错误
> > > > 
> > > > 
> > > > 我是淘宝8.7.1.1的版本，你是9.5还是最新？
> > > 
> > > 
> > > 9.5的
> > 
> > 
> > 我把拍猫的代码单独用vccode运行，居然可以拍猫，但是拍了可能一百下左右，再拍就没有反映了，淘宝可能不能一直拍吧？你有试过可以拍多少下？
> 
> 666下，没跑完就没收益了，但是它会跟你互动

多少下你都知道的吗！！！

**Comment by CfortWang** [comment]
> > > > > > 奇怪诶 我没遇到过也没法复现你觉得错误
> > > > > 
> > > > > 
> > > > > 我是淘宝8.7.1.1的版本，你是9.5还是最新？
> > > > 
> > > > 
> > > > 9.5的
> > > 
> > > 
> > > 我把拍猫的代码单独用vccode运行，居然可以拍猫，但是拍了可能一百下左右，再拍就没有反映了，淘宝可能不能一直拍吧？你有试过可以拍多少下？
> > 
> > 
> > 666下，没跑完就没收益了，但是它会跟你互动
> 
> 多少下你都知道的吗！！！

不是，我的意思是我输入的是666，但是没等跑完就已经没收益了

**Comment by iblue007** [comment]
> > > > > > > 奇怪诶 我没遇到过也没法复现你觉得错误
> > > > > > 
> > > > > > 
> > > > > > 我是淘宝8.7.1.1的版本，你是9.5还是最新？
> > > > > 
> > > > > 
> > > > > 9.5的
> > > > 
> > > > 
> > > > 我把拍猫的代码单独用vccode运行，居然可以拍猫，但是拍了可能一百下左右，再拍就没有反映了，淘宝可能不能一直拍吧？你有试过可以拍多少下？
> > > 
> > > 
> > > 666下，没跑完就没收益了，但是它会跟你互动
> > 
> > 
> > 多少下你都知道的吗！！！
> 
> 不是，我的意思是我输入的是666，但是没等跑完就已经没收益了

差不多 我可能也就点了300-400不到就没了

**Comment by iblue007** [comment]
> > > > > 奇怪诶 我没遇到过也没法复现你觉得错误
> > > > 
> > > > 
> > > > 我是淘宝8.7.1.1的版本，你是9.5还是最新？
> > > 
> > > 
> > > 9.5的
> > 
> > 
> > 我把拍猫的代码单独用vccode运行，居然可以拍猫，但是拍了可能一百下左右，再拍就没有反映了，淘宝可能不能一直拍吧？你有试过可以拍多少下？
> 
> 我拍一千下，后来再拍就没钱了

我刚刚试了一下，如果我弹窗输入拍的次数的话，点猫猫就不行，但是如果我注释点代码，次数直接写死的话，就可以拍猫了，这是什么原因，你知道吗？（就是这个代码 var num = 50;//rawInput("输入拍猫次数（中途不可退，次数别太多）,输入-1退出");）

**Comment by jayeew** [comment]
> > > > > > 奇怪诶 我没遇到过也没法复现你觉得错误
> > > > > 
> > > > > 
> > > > > 我是淘宝8.7.1.1的版本，你是9.5还是最新？
> > > > 
> > > > 
> > > > 9.5的
> > > 
> > > 
> > > 我把拍猫的代码单独用vccode运行，居然可以拍猫，但是拍了可能一百下左右，再拍就没有反映了，淘宝可能不能一直拍吧？你有试过可以拍多少下？
> > 
> > 
> > 我拍一千下，后来再拍就没钱了
> 
> 我刚刚试了一下，如果我弹窗输入拍的次数的话，点猫猫就不行，但是如果我注释点代码，次数直接写死的话，就可以拍猫了，这是什么原因，你知道吗？（就是这个代码 var num = 50;//rawInput("输入拍猫次数（中途不可退，次数别太多）,输入-1退出");）

这就触及到我的盲区了哈哈，那你就自己写死吧 问题不大
