### ISSUE TITLE
一个新窍门：手机新版淘宝卸载

### ISSUE THREAD

**Issue by Pythonpa** [jiayiwang5/TaoBaoScripts#32]
关于新版淘宝卸载不干净的，还有个稍微简便的方式，就是手机连接电脑后，全局搜索taobao相关的字样，把卸载后残留全部手动删除干净，或者有些优化软件应该也能做到，我试验了下，没按作者的卸载方式，全局删除taobao字样的文件包，也能正常运行脚本，供参考。低调，低调~~

**Comment by jayeew** [comment]
谢谢反馈
