### ISSUE TITLE
导入文件后运行报错 Type Error：Cannot find function waitFor in object

### ISSUE THREAD

**Issue by quinnsu** [jiayiwang5/TaoBaoScripts#34]
小白求教
![Screenshot_20201026_120108_com stardust scriptdro](https://user-images.githubusercontent.com/67184811/97132810-fba4c900-1782-11eb-9f24-4690834f45dc.jpg)

**Comment by jayeew** [comment]
手机，系统，都是什么

**Comment by quinnsu** [comment]
华为nova，Android 9 ，Autojs版本是3.0.0 Alpha40（网上找的……

**Comment by jayeew** [comment]
> 华为nova，Android 9 ，Autojs版本是3.0.0 Alpha40（网上找的……

auto.js换成4，我库里提供了

**Comment by quinnsu** [comment]
okok成功了，我没认真看readme文件，太感谢啦~~
