### ISSUE TITLE
 拼多多晚8点活动0元秒杀 问题

### ISSUE THREAD

**Issue by jahnli** [jiayiwang5/TaoBaoScripts#36]
请问  拼多多晚8点活动0元秒杀 的活动入口在哪， 目前只有1元秒杀和9.9秒杀 ，而且不只是晚上8点才有。

**Comment by jayeew** [comment]
打开最新版拼多多，首页，往下滑动页面，滑个三五下在右侧会出现（百万现金红包）小窗，点进去就是。建议兑换200钻到500钻实物，成功率高。

**Comment by jahnli** [comment]
现在是1111元车队红包 ， 没有百万现金红包

**Comment by jayeew** [comment]
> 现在是1111元车队红包 ， 没有百万现金红包

首页直接搜索 （多多精灵） 试试?

**Comment by jahnli** [comment]
已找到，请问有没有主动领钻的软件。

**Comment by jayeew** [comment]
> 已找到，请问有没有主动领钻的软件。

有自用的，你也太懒了吧（小声说，，）

**Comment by jahnli** [comment]
0.0. 我发现到每次才给9个钻。。。得到200

**Comment by jayeew** [comment]
> 0.0. 我发现到每次才给9个钻。。。得到200

每天几个任务大概90～100钻

**Comment by jahnli** [comment]
ok 感谢
