### ISSUE TITLE
执行顺序问题，去完成会卡住，因为分享任务的原因

### ISSUE THREAD

**Issue by jw-star** [jiayiwang5/TaoBaoScripts#37]
mission("去浏览");
        mission("去完成");
        mission("去逛逛");
        mission("去搜索");

**Comment by jayeew** [comment]
可能又出新任务了吧，我跑的时候是没有的，今天任务也都做完了，明天任务一刷新我就改改。

**Comment by jayeew** [comment]
大致看了下，不知道可不可行，你把mission函数第二行start=1,改成start+=1试试?

**Comment by jw-star** [comment]
> 大致看了下，不知道可不可行，你把mission函数第二行start=1,改成start+=1试试?

可以看下这段代码，他写的是跳过分享的任务
` if (textContains("复制链接").exists()) {
                        log("跳过分享任务");
                        j++;
                        i++;
                        back();
                        sleep(200 * speed);
                        back();
                        break;
                    }`

**Comment by jw-star** [comment]
> 大致看了下，不知道可不可行，你把mission函数第二行start=1,改成start+=1试试?

```
 if (textContains("淘宝特价版送红包").exists()) {
                        log("跳过打开APP任务");
                        j++;
                        i++;
                        back();
                        break;
                    }
```

**Comment by jayeew** [comment]
不用看了 没什么 就是我这没刷出这个任务我就没考虑到而已，改成我说的那样八成就解决了
