### ISSUE TITLE
淘宝9.5.6  测试失效，不知道还有解决办法不

### ISSUE THREAD

**Issue by jw-star** [jiayiwang5/TaoBaoScripts#38]

**Comment by jayeew** [comment]
??我跑了俩任务试试还能全奖励啊，你那又几百块了吗

**Comment by jiayiwang5** [comment]
??我跑了俩任务试试还能全奖励啊，你那又几百块了吗

**Comment by jayeew** [comment]
试了试任务能正常，小bug我待会修复，你是不是后台自动更新淘宝最新版了

**Comment by OceanSadness** [comment]
我这边试了一下也失效了

**Comment by OceanSadness** [comment]
只有100金币

**Comment by jayeew** [comment]
我靠 什么情况，我刚点了几十万币啊，难不成分批黑

**Comment by jw-star** [comment]
> 我靠 什么情况，我刚点了几十万币啊，难不成分批黑

8.9.2可以用倒是

**Comment by jayeew** [comment]
淘宝真坑，蚊子腿儿还最严，东哥一天十几块

**Comment by koen100** [comment]
9.5黑号, 降低到8.11还然是黑号. 最后换到ios仍然是黑号,我号没了.淘宝一生黑

**Comment by jayeew** [comment]
> 9.5黑号, 降低到8.11还然是黑号. 最后换到ios仍然是黑号,我号没了.淘宝一生黑

对不住了兄弟，我还没黑但也不敢用了

**Comment by koen100** [comment]
作者辛苦了，这事就是淘宝不厚道。

**Comment by jshazlt** [comment]
幸苦了，感谢分享

**Comment by koen100** [comment]
经测试,安卓tb删除数据 升级到最新版本，把脚本卸载后，手动可以正常领奖励了.
但用ios手动还是黑号

**Comment by jayeew** [comment]
> 经测试,安卓tb删除数据 升级到最新版本，把脚本卸载后，手动可以正常领奖励了.
> 但用ios手动还是黑号

听说ios捷径可以刷淘宝 你可以试试

**Comment by koen100** [comment]
ios手动都黑号, 捷径可以逃过制裁吗

**Comment by mustssr** [comment]
刚刚用完脚本9.5.17，金币正常，难道还真的分批封?

**Comment by jw-star** [comment]
..
