### ISSUE TITLE
执行到一半

### ISSUE THREAD

**Issue by ailongIdo** [jiayiwang5/TaoBaoScripts#4]
我这边速度是1  执行完第一个任务就停止了

**Comment by Peehsa** [comment]
建议把前面的搜索任务代码都删去，直接从赚猫币开始

**Comment by jayeew** [comment]
> 我这边速度是1 执行完第一个任务就停止了

速度太快了，建议2或3

**Comment by Peehsa** [comment]
> > 我这边速度是1 执行完第一个任务就停止了
> 
> 速度太快了，建议2或3

速度太快，点击输入框后会跳出输入法，会打断操作...

**Comment by jayeew** [comment]
> > > 我这边速度是1 执行完第一个任务就停止了
> > 
> > 
> > 速度太快了，建议2或3
> 
> 速度太快，点击输入框后会跳出输入法，会打断操作...

所以你正常工作了吗

**Comment by Peehsa** [comment]
> > > > 我这边速度是1 执行完第一个任务就停止了
> > > 
> > > 
> > > 速度太快了，建议2或3
> > 
> > 
> > 速度太快，点击输入框后会跳出输入法，会打断操作...
> 
> 所以你正常工作了吗

我搞定了。不过我还有个小问题。“去完成”哪里有一个//if(text("50000")  //这是啥？

**Comment by jayeew** [comment]
> > > > > 我这边速度是1 执行完第一个任务就停止了
> > > > 
> > > > 
> > > > 速度太快了，建议2或3
> > > 
> > > 
> > > 速度太快，点击输入框后会跳出输入法，会打断操作...
> > 
> > 
> > 所以你正常工作了吗
> 
> 我搞定了。不过我还有个小问题。“去完成”哪里有一个//if(text("50000") //这是啥？

有可能在升级过程中跳出一个领勋章页面，这样可以捕捉关闭它

**Comment by FayeVrans** [comment]
反复进入退出淘宝家园

**Comment by jayeew** [comment]
> 反复进入退出淘宝家园

请问日志卡到哪里了

**Comment by FayeVrans** [comment]
> > 反复进入退出淘宝家园
> 
> 请问日志卡到哪里了

"开始执行任务"
