### ISSUE TITLE
求做一个auto.js的拼多多里面的我的脚步任务脚本,

### ISSUE THREAD

**Issue by lqhorochi** [jiayiwang5/TaoBaoScripts#42]
求做一个auto.js的拼多多里面的我的脚步任务脚本,
平时任务太多,做不来,希望做一个auto.js脚本

**Comment by jayeew** [comment]
> 求做一个auto.js的拼多多里面的我的脚步任务脚本,
> 平时任务太多,做不来,希望做一个auto.js脚本

我太懒怎么办，，，
