### ISSUE TITLE
怎么下载这个js脚本呀

### ISSUE THREAD

**Issue by el-sl** [jiayiwang5/TaoBaoScripts#6]
main.js
楼主，怎么下载呀，不会用呀，软件我下载好了，这个main.js怎么下载下来！

**Comment by jayeew** [comment]
， ，，右上角download

**Comment by el-sl** [comment]
没有找到 download 呀！





&nbsp;

一棵树，一根草，一束花，一把土……使得时间似乎凝固，只有墙上的钟告诉你生命在延续。&nbsp;&nbsp; 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jayeewong"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 上午10:37
收件人: "jiayiwang5/TaoBaoScripts"<TaoBaoScripts@noreply.github.com&gt;; 
抄送: "董国锋"<19631295@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jiayiwang5/TaoBaoScripts] 怎么下载这个js脚本呀 (#6)





 
， ，，右上角download
