### ISSUE TITLE
悬浮窗没有文字

### ISSUE THREAD

**Issue by Perplexed-H** [jiayiwang5/TaoBaoScripts#7]
悬浮窗没有文字，和图片中的不一样；
拍猫怎么触发，我只触发过一次，再就没了

**Comment by jayeew** [comment]
请问你是在淘宝进程未开启情况下启动脚本吗

**Comment by Perplexed-H** [comment]
对

**Comment by jayeew** [comment]
> 对

延迟设定多少

**Comment by Perplexed-H** [comment]
> 
> 
> > 对
> 
> 延迟设定多少

最初设置3，有些复杂页面时间不够，就设了5

**Comment by jayeew** [comment]
> > > 对
> > 
> > 
> > 延迟设定多少
> 
> 最初设置3，有些复杂页面时间不够，就设了5

请运行新脚本，并告诉我日志内容，谢谢反馈

**Comment by Perplexed-H** [comment]
每次都需要手工调整，有时候可能会退出活动页；
浏览任务完成后没有提示升级与拍猫
