### ISSUE TITLE
浏览任务已经完成，后面就不动了

### ISSUE THREAD

**Issue by diy01** [jiayiwang5/TaoBaoScripts#8]

**Comment by jayeew** [comment]
卡在哪不动，猫拍了吗

**Comment by wanglp4585** [comment]
我的是停留在这个界面，还没有进行拍猫，看看能不能有帮助
![QQ图片20201021105205](https://user-images.githubusercontent.com/35189368/96667353-82286780-138b-11eb-8e68-5920039d3bff.jpg)

**Comment by jayeew** [comment]
> 我的是停留在这个界面，还没有进行拍猫，看看能不能有帮助
> ![QQ图片20201021105205](https://user-images.githubusercontent.com/35189368/96667353-82286780-138b-11eb-8e68-5920039d3bff.jpg)

请下载新脚本试试
