### ISSUE TITLE
右上角没有你说的download呀！如下图

### ISSUE THREAD

**Issue by el-sl** [jiayiwang5/TaoBaoScripts#9]
main.js
楼主，怎么下载呀，不会用呀，软件我下载好了，这个main.js怎么下载下来！
右上角没有你说的download呀！如下图
![图片](https://user-images.githubusercontent.com/68845324/96667110-ff071180-138a-11eb-8bd0-9ceec50406f1.png)

**Comment by zjhxmjl** [comment]
git clone or gzip for github

**Comment by el-sl** [comment]
Can you mark it on the diagram?

THANKS！

**Comment by el-sl** [comment]
I'm so sorry，I haven't used Github

**Comment by jayeew** [comment]
项目首页，右上角绿色 code 按钮，点开，下载

**Comment by el-sl** [comment]
原来如此，尴尬了，我使劲的在代码页找！
&nbsp;

一棵树，一根草，一束花，一把土……使得时间似乎凝固，只有墙上的钟告诉你生命在延续。&nbsp;&nbsp; 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jayeewong"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 中午11:00
收件人: "jiayiwang5/TaoBaoScripts"<TaoBaoScripts@noreply.github.com&gt;; 
抄送: "董国锋"<19631295@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jiayiwang5/TaoBaoScripts] 右上角没有你说的download呀！如下图 (#9)





 
项目首页，右上角绿色 code 按钮，点开，下载
